### PR TITLE
Update 2/5/2016 Electrical section completed

### PR DESCRIPTION
**Pull request by ahmedsami1406**

### CODE REVIEW

**Comment by ahmedsami1406** [comment]
mechanical section completed also
Alhamdulillah (All praises are yo ALLAH)

**Comment by xie-dongping** [comment]
@mtiller 
Mike, I'll merge it and add to the CI, if you are ok with it.

**Comment by xogeny** [comment]
@xie-dongping Fine with me.  Thanks.

**Comment by xie-dongping** [comment]
@ahmedsami1406 
I just ran a quick test with the arabic translation, and I notices a few points that the translation package `sphinx-intl` doesn't like. As I don't know arabic, you might want to look into them:
* Almost all translation paragraphs begin with a space ` `, but the `sphinx-intl` (at least the version we are using now) somehow ignores all the translation strings if it is so. I'm not exactly sure if it is necessary for Arabic, but if it is the case, we would have to find a solution for it. If is just nice to have, then I would suggest removing all the spaces at the beginning of the paragraph (just the ones directly after `msgstr ""` has to be removed.
* There are some hard returns `\n` in the translation text, and I'm not really sure if it is 100% necessary. From my personal experience, I would suggest removing them if possible. Just my 2 cents.

**Comment by ahmedsami1406** [comment]
the first point about space in the beginning of every line is because I forget to make a space after the last word in the previous line> If this space is deleted the last word of the previous line will be stacked to the first word in the current line for example

the second point about \n
it is used and necessary because the arabic writing is from right to left and so if you tried to write an english word in the middle of an arabic line the line will be mirrored > the last part will be the first and the first will be the last
also braces ( ) may cause problem because of right to left direction > and i use - - instead

**Comment by ahmedsami1406** [comment]
I am using almaany.com web site
http://www.almaany.com/
and freetranslation.com web site
https://www.freetranslation.com/

to translate and then i use my arabic language and engineering knowledge to make the speech easy to understand for the most of arabic audience> there are differences between arabic languages like english languages (american or british) so i try to be clear for all arabic audience> some times i increase the words for that like translating
angular acceleration to
التسارع الزاوي أو العجلة الزاويّة

or relative angular velocity
السرعة الزاوية الدورانية النسبية

I also tried to make this term clear in the additional section of me called
Used Terms المصطلحات المستخدمة

**Comment by ahmedsami1406** [comment]
the additional
Used Terms المصطلحات المستخدمة
section in every article is necessary because the egyptian arabic terms in engineering is different from syrian terms , iraqi terms and so on> so, some readers may not understand what you want to say if you did not do that> so, most of engineering arabic books add this section in the end or in the last sections in there books> I prefer to add it to every article because the book is very big and beacause of hyper-linking usage> my english language is not very good bu my arabic language is very good or that what i think because most of my study and reading was in arabic language> my translation is not professional and i tried to get help from dr lutfi al-sharif the famous mechatronics professor and from others but i did not get the help till now> so, i invited in a translated presentation people to participate with me on git hub>
This is the link of translated presentaion
http://kutub.info/library/book/19510

**Comment by ahmedsami1406** [comment]
I ask the goodness from ALLAH

I am pleased to cooperate with you all> and I will be happy to take any comment or advice about translation or revision from arabic expert Insha'ALLAH

**Comment by xie-dongping** [comment]
@ahmedsami1406 
Thanks for the clarification! 

As the first point is only a problem when you have spaces at the FIRST lines of each translated string. Take `text/locale/ar/LC_MESSAGES/behavior/equations/physical.po` as example, it is a problem with the first space on `line 28` `line 45` but not on `line 29` `line 30` or `line 47`. Only when the space at the removed accordingly, can the system display the translated text.

The build for `ar` and `es` was not successful last night at the continuous integration system. But this link should work tomorrow [http://cnbook.s3-website-ap-northeast-1.amazonaws.com/ar/](http://cnbook.s3-website-ap-northeast-1.amazonaws.com/ar/)

**Comment by xie-dongping** [comment]
The second point about 

Do you have a unix-like system (Linux, MacOSx or FreeBSD) to test locally? Wait for the continuous integration system may work, to have a local build system might be faster for you to test some small syntax issues. 

If you would like to set the build system up locally, I would be happy to provide more details.

**Comment by ahmedsami1406** [comment]
I am working on Waha Linux which is an arabic version built on Debian Linux > but I don't know how to build the syntax

**Comment by ahmedsami1406** [comment]
I will try to delete the unwanted spaces Insha'ALLAH Now

**Comment by xie-dongping** [comment]
First install the dependencies:
```
sudo apt-get install -y wget
for deb in deb deb-src; do echo "$deb http://build.openmodelica.org/apt `lsb_release -cs` stable"; done | sudo tee /etc/apt/sources.list.d/openmodelica.list
wget -q http://build.openmodelica.org/apt/openmodelica.asc -O- | sudo apt-key add - 
sudo apt-get update
sudo apt-get install -y openmodelica

sudo apt-get install -y python python-dev python-pip python-virtualenv
sudo apt-get install -y calibre librsvg2-bin texlive-fonts-recommended
sudo apt-get install -y texlive-latex-recommended texlive-latex-extra
sudo apt-get install -y python-matplotlib python-pip python-scipy
sudo apt-get install -y python-sphinx python-jinja2 s3cmd

pip install --user --upgrade 'sphinx-intl==0.9.6'
pip install --user --upgrade 'sphinx==1.3'
pip install --user --upgrade s3cmd

pip install --user --upgrade https://bitbucket.org/dietmarw/pygments-main/get/default.tar.gz
```

Then you can build the project with:
```
git clone https://github.com/xogeny/ModelicaBook.git
cd ModelicaBook/text
make specs
make results
make dirhtml
make dirhtml_ar
make server_ar
```
Then the result would be accessible at `http://127.0.0.1:8000/`.

**Comment by ahmedsami1406** [comment]
OK I will try Insha'ALLAH

**Comment by ahmedsami1406** [comment]
Thank You very much :)

**Comment by ahmedsami1406** [comment]
I Think that I deleted all unwanted spaces or most of them>
Should I make a pull request now ?

**Pull request merged**
