### PR TITLE
Bug fixe, Architecture Thermal: Redeclare modifiers

### PR DESCRIPTION
**Pull request by xie-dongping**
Bugs for redeclare with inheritance and modifiers at the base model.
Affects model OnOffVariant.mo and HysteresisVariant.mo

Remove the modifier in ExpandableModel and put to the controller
component as default parameters.

Should resolve issue #294

### CODE REVIEW

**Comment by xogeny** [comment]
Something isn't right here.  Unfortunately, I don't have time right now to dig into it.  I'm not sure why this error just popped up in OM.  I suspect some of these modifiers need to be moved to the `constrainedby` clause (or that the `constrainedby` needs to be listed explicitly).  Perhaps @sjoelund has a comment here?

**Comment by sjoelund** [comment]
Yes, if not all models redeclaring the controller will have k, constrainedby should probably be used instead. I don't know who changed instantiation here. Probably @perost or @adrpo.

**Comment by xogeny** [comment]
So the bottom line is that the code needs to be refactored so that the `k`, `setpoint` and `T` are all specific to the `ExpandablePIControl`.  More importantly, it shouldn't be implicitly assumed that the new constraint involves `ExpandablePIControl`.  My guess is that the redeclaration should be written something like this:

```
redeclare replaceable Implementations.ExpandablePIControl controller(setpoint=300, k=20, T=1)) constrainedby Interfaces.ControlSystem_WithExpandableBus;
```

This way, the modifications are applied only to the `ExpandablePIControl` instance and the constrain is maintained as `Interfaces.ControlSystem_WithExpandableBus`.

I don't have time to test it right now because I'm about to be out of town for a week.  But that looks about right to me... @sjoelund, @dietmarw, perost (not a GitHub ID, BTW) and @adrpo, what do you think? Is that the issue?

@sjoelund and @adrpo Getting this working is a fairly high priority because it is preventing us from getting the CircleCI stuff running smoothly.  Once that is done, I think we'll have a very nice path for a) doing CI testing on the material in the book and b) a way to automatically deploy new versions of the book in both HTML and electronic form.  So this is a really big improvement that @xie-dongping has implemented.  So I'd like to get it working soon.  Thanks for any help that the OM team can provide.

**Comment by perost** [comment]
I'm probably partially responsible for this. Previously we simply ignored modifiers on constrainedby, and most models "worked". Then I fixed the instantiation some time ago so that we also consider constrainedby modifiers. A week ago I found some issues with this and improved it, so in case you don't have an up-to-date OM installation you should try these models again.

If you've tried with the latest nightly build and it still doesn't work, please submit a ticket to our [trac](https://trac.openmodelica.org/OpenModelica) and assign it to me (preferably with a small model that shows the issue).

**Comment by xie-dongping** [comment]
@perost 
Thanks for the clarification! 

I'll try them out and see if everything works.

**Comment by xogeny** [comment]
I've forgotten the exactly semantics of what happens to the constraining clause when you redeclare things.  With the current code, it seems like the constraining class is getting redefined *and* the modifiers on the instance are getting moved to the constraining class.  I'm not sure what the spec says about this case (i.e., where the modifiers go when no constraining class is specified or what the new constraining class is when an already `replaceable` component, which would already have a constraining class, gets redeclared).

So definitely try out the latest version as @perost suggests.  But in case that doesn't work, we'll have to rewrite this code to follow the semantics in the spec (whatever those are...perhaps @perost can enlighten us on this corner case).

**Comment by xie-dongping** [comment]
@perost @xogeny 
I've tried out with OpenModelica `1.9.4~dev.beta1-62-ge761284` from the Ubuntu nightly. 

It seems that the model `ModelicaByExample.Architectures.ThermalControl.Examples.OnOffVariant` works now when adapting the following changes in its base model `ExpandableModel`:

```
diff --git a/ModelicaByExample/Architectures/ThermalControl/Examples/ExpandableModel.mo b/ModelicaByExample/Architectures/ThermalControl/Examples/ExpandableModel.mo
index 5d9c1bb..e81245b 100644
--- a/ModelicaByExample/Architectures/ThermalControl/Examples/ExpandableModel.mo
+++ b/ModelicaByExample/Architectures/ThermalControl/Examples/ExpandableModel.mo
@@ -5,6 +5,7 @@ model ExpandableModel "Thermal system using expandable bus architecture"
       C=2, G=1, T_ambient=278.15, h=2),
     redeclare replaceable Implementations.ContinuousActuator actuator,
     redeclare replaceable Implementations.TemperatureSensor sensor,
-    redeclare replaceable Implementations.ExpandablePIControl controller(
-      setpoint=300, k=20, T=1));
+    redeclare replaceable Implementations.ExpandablePIControl
+      controller(setpoint=300, k=20, T=1)
+      constrainedby Interfaces.ControlSystem_WithExpandableBus);
 end ExpandableModel;
```

However, the model `ModelicaByExample.Architectures.ThermalControl.Examples.HysteresisVariant` which extends and redeclares the `OnOffVariant` still doesn't work.

I tried to assemble a simple example with inheritance + constrainedby but to no avail. The simple example works as it should. Only the model in the `ModelicaByExample` has such pecularities.

**Comment by xogeny** [comment]
@xie-dongping's recent changes look right to me (modifiers on the `controller`, not on the constraint). Any comments from @perost or @sjoelund as to why that version doesn't work?

**Comment by xogeny** [comment]
Is this PR up to date?  I don't see any changes involving `constrainedby` in the PR?  It would probably be good to update it to what we think it *should* look like (even of OM rejects it).

**Comment by xie-dongping** [comment]
The PR is not up to date if we want to use modifiers in `constrainedby` clause.

However, it certainly work in any version of OM. @xogeny , it is up to you to decide which one you want to include. I can push the `constrainedby` version instead.

**Comment by xogeny** [comment]
It looks like what you've done with this PR is to just provide the parameter values as defaults in the underlying models.  My position is that the modifiers should be kept when the instances are declared but the constraining class should be preserved in each successive redeclaration.  This is, as far as I can tell, what you've done with the `diff` you showed in the comments above.  So that is the version I want in the book.  So I'd suggest switching the PR to reflect that approach and then we can see where we stand with OM compliance.

**Comment by xie-dongping** [comment]
@xogeny 
[Bug reported to OpenModelica trac.](https://trac.openmodelica.org/OpenModelica/ticket/3750#ticket)

And you might want to merge this PR since now it is what it should like.

**Comment by xie-dongping** [comment]
@xogeny 
I don't know how long does it take to close a bug in OpenModelica. If it takes long, maybe a quickfix is better since it would then compile, and give us a working CI system.

**Comment by dietmarw** [comment]
@xie-dongping So is this PR still needed or not in order to get CI going?

**Comment by xie-dongping** [comment]
In order to get the CI going, we would gave to ignore it for now. Only when the bug in OM is fixed some days later can we merge it. Or else we break the CI.

Merging the other PRs should the CI going.

**Comment by dietmarw** [comment]
The original issue that this PR is addressing is actually resolved upstream on OM's side. So this quickfix-PR is no longer necessary.

**Pull request closed without merging**
