### PR TITLE
Fix index-out-of-bounds exception

### PR DESCRIPTION
**Pull request by tbeu**

### CODE REVIEW

**Comment by xogeny** [comment]
@tbeu, just so I understand your fix here.  The point is that this will still generate an error when the value is out of bounds.  But it won't trigger an out-of-bounds exception after signaling the error.  Is that correct?

Wouldn't another solution be to simply return (e.g., 0) after calling `ModelicaFormatError`?  I think you know more about the semantic implications here than I do.  That is why I'm asking.

**Comment by tbeu** [comment]
I tried to simulate ExtObjInitTest.V1 of [#1705](https://trac.modelica.org/Modelica/ticket/1705) with the current VectorTable.c and noticed that it gives wrong result for x[table->npoints-1].

**Comment by xogeny** [comment]
So is the issue related to interactions with a non-linear solver?  My recollection is that this table doesn't extrapolate.  So any request for a value outside the independent variable range specified for the table is an error.  If that happens during non-linear iteration, the tool should recognize that the solution it gets is not valid.

So I can understand that the code should be fixed so that it never makes an out-of-bounds array access.  But my point is that it **should not matter** what value it returns in the case where the independent variable is outside the expected range as long as it calls `ModelicaFormatError`.  Do you agree?

**Comment by tbeu** [comment]
This is neither about extrapolation nor solving non-linear equations.

ExtObjInitTest.V1 gives a wrong result at the upper bound of the sampling points due to i being out of bounds.

**Comment by xogeny** [comment]
But do you agree that simply returning zero immediately following the call to `ModelicaFormatError` would be an equivalent solution.  Keep in mind, I don't have a problem with your solution either.  I just want to make sure I understand what you are trying to accomplish with your fix.

**Comment by sjoelund** [comment]
Returning something after Modelica...Error is pointless. It's a noreturn function.

**Comment by xogeny** [comment]
@sjoelund Huh?  I'm not talking about Modelica...Error returning something. I'm talking about `interpolateVectorTable`...it definitely returns a double.  I'm just trying to make sure we all agree that if you call `ModelicaFormatError` it should not matter what `interpolateVectorTable` returns.

**Comment by sjoelund** [comment]
If you try to return something after ModelicaError, the C compiler will detect that you have an unreachable return statement and you might get a warning. ModelicaError does not return, so you shouldn't have a return statement after it.

**Comment by xogeny** [comment]
@sjoelund Several points.  First, I am not advocating putting a return after `Modelica...Error`.  I am simply trying to make sure we all agree it would be equivalent to the solution proposed by @tbeu.  Second, is it actually stated in the specification that `Modelica...Error` **must** be implemented in that way?  If not, then I don't see why you need to worry about such warnings.

My concern, w.r.t. to @tbeu's fix, is that it might imply to people that some additional computations are necessary to return a "proper" return value when, in fact, it doesn't matter.  If we added a:

```
return 0; // Return value doesn't matter in the case of an error
```

after the call to `Modelica...Error` it might be easier for people to understand the code which is the point.  In the end, I want something that is clear (for the reader) and for the compiler.  But if I have to choose between them, I want it clear for the reader.

**Comment by tbeu** [comment]
Again, this is not about extrapolation. Simply construct a VectorTable with {{0,0},{1,1}} and see what interpolateVectorTable returns at 1. You'll hopefully see, that index i (as used in interpolateVectorTable is greater than 1).

**Comment by sjoelund** [comment]
Yes, the spec says ModelicaError never returns. This means it is an implementation error if the ModelicaError call does return. The MSL ModelicaUtilities.h also specifies the noreturn attributes on the function. So you should expect warnings when compiling code that assumes such a function returns.

**Comment by xogeny** [comment]
@sjoelund My point here is...if `ModelicaFormatError` never returns, then @tbeu's changes should never matter, right?  I mean the `ModelicaFormatError` call occurs if `x<table->x[0]` or `x>table->x[table->npoints-1]`.  So we know that if `x` is outside the possible values of `x`, `ModelicaFormatError` will get called and, presumably, never return.

So what is the purpose of these changes?  Either a) some compilers don't honor the `noreturn` aspect of `ModelicaFormatError` and these changes compensate for that, b) these changes have no effect or c) I'm misunderstanding something.

**Comment by sjoelund** [comment]
@tbeu using the given example model, you can a nice working simulation that stops at time=1. If you give a stopTime>1, you get (in OpenModelica):
```
stdout            | info    | Request to compute value of y at 1
stdout            | info    | Request to compute value of y at 1.002
assert            | debug   | Requested value of x=1.002 is above the upper bound of 1
stdout            | info    | Request to compute value of y at 1
stdout            | warning | Integrator attempt to handle a problem with a called assert.
stdout            | info    | Request to compute value of y at 1.001
assert            | debug   | Requested value of x=1.001 is above the upper bound of 1
stdout            | info    | model terminate | Simulation terminated by an assert at time: 1.001
```

And the changes made in this pull request does not change anything (because the above assertions work as they should and the code in the pull request in never reached). So, @xogeny I guess it is b) that is true and some tools do not comply with the description of the ModelicaError functions.

**Comment by tbeu** [comment]
```
stdout            | info    | Request to compute value of y at 1
```
What is the output if the VectorTable is constructed with {{0,0},{1,1}}?

**Comment by sjoelund** [comment]
{{0,0},{1,1}} is what I enforced:
```
  model V1 "Correct, if y at time=1 is 0.73908513321515"
    parameter Real x(fixed=false, start=0.25);
    Real y;
    protected
      VectorTable v=VectorTable({{0,0},{1,1}});
    initial equation
      x = cos(x);
    equation
      y = interpol(v, time);
    annotation(experiment(StopTime=2));
  end V1;
```

**Comment by tbeu** [comment]
What is y at time=1?

**Comment by sjoelund** [comment]
```
stdout            | info    | Request to compute value of y at 1
stdout            | info    | Computed y=1.5859507231504e-321
```

**Comment by tbeu** [comment]
Bingo!

**Comment by sjoelund** [comment]
Ah, when I ran valgrind the model had the stopTime=1 from the original model. Yes, it is reading beyond the limits and probably the pull request is correct and actually fixes the problem. The alternative would be to disallow 1 here, but I suppose interpolation between 0 and 1 should include both 0 and 1.

**Comment by xogeny** [comment]
OK, merging this since I don't see any real objections.  I suspect there might be a clearer way to express this, but I'm concerned that we may end up wrestling with the compiler and warnings about unreachable code if we make it more readable.

**Comment by tbeu** [comment]
Finally, thanks.

**Pull request merged**
