### PR TITLE
deleting all \n's except in "-Used Terms-"

### PR DESCRIPTION
**Pull request by ahmedsami1406**

### CODE REVIEW

**Comment by ahmedsami1406** [comment]
I have a very little experience about HTML and Proxy
So, Can I postpone the CSS and proxy for now?

I want to continue translation for now
and make other thing later
Insha'ALLAH

Is that ok for you
@xie-dongping

**Comment by xie-dongping** [comment]
Sure, it is not so urgent for now.

Ahmed Sami <notifications@github.com>于2016年5月10日周二 20:02写道：

**Comment by ahmedsami1406** [comment]
thank you> then, I will continue translation Insha'ALLAH

**Comment by ahmedsami1406** [comment]
Is this translation Is good

`Law of Mass Action "
"<http://en.wikipedia.org/wiki/Law_of_mass_action>`_ [Guldberg]_.

"`قانون فاعلية الكتلة لجولدبرج "
"<https://ar.wikipedia.org/wiki/%D9%82%D8%A7%D9%86%D9%88%D9%86_%D9%81%D8%A7%D8%B9%D9%84%D9%8A%D8%A9_%D8%A7%D9%84%D9%83%D8%AA%D9%84%D8%A9>`_ [Guldberg]_."

I have changed the link to the arabic wikipedia link of law of mass action

**Comment by dietmarw** [comment]
Yes sure. I think it is a good idea to link to the localised Wikipedia pages when they exist. :+1:

**Comment by ahmedsami1406** [comment]
@xie-dongping 
@dietmarw 

thank you very much

**Comment by ahmedsami1406** [comment]
@xie-dongping 
@dietmarw 
@mtiller 
and others

I want to thank you for supporting poor people Engineering (Charity Engineering)

**Comment by ahmedsami1406** [comment]
my friend sent to me this link
but I am sorry that I feel this very hard to understand

https://www.w3.org/International/questions/qa-html-dir#rtlsetup

**Comment by xie-dongping** [comment]
@ahmedsami1406 
You can follow this site for a quick fix:
[http://docutils.sourceforge.net/FAQ.html#can-i-produce-documents-in-right-to-left-languages](http://docutils.sourceforge.net/FAQ.html#can-i-produce-documents-in-right-to-left-languages)

You can test the css changes with the developer tools in Firefox and then write it down as a css file. Like this:
[https://www.youtube.com/watch?v=qZRLqpJiUsI)[https://www.youtube.com/watch?v=qZRLqpJiUsI]
and this:
[https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_and_edit_CSS](https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_and_edit_CSS)

With the method I told you last time, you may change inject the new css file to the site and make it work.

**Comment by ahmedsami1406** [comment]
Thank you all

**Pull request merged**
