### PR TITLE
Delete the Unwanted Spaces which is before the first line or after \n and before a line

### PR DESCRIPTION
**Pull request by ahmedsami1406**

### CODE REVIEW

**Comment by xie-dongping** [comment]
Thanks! Let's see if it works in CI build.

**Comment by xie-dongping** [comment]
@ahmedsami1406 
Now it works:
[http://cnbook.s3-website-ap-northeast-1.amazonaws.com/ar/behavior/equations/first_order/](http://cnbook.s3-website-ap-northeast-1.amazonaws.com/ar/behavior/equations/first_order/)

**Comment by ahmedsami1406** [comment]
@xie-dongping 
yes it works very good
but the missing thing is the direction of writing
the direction is from left to right and it should be from right to left
in word it is easy by this button


every line who has an english letter or word in it is mirrored by this letter or word

I have downloaded open modelica by deb packages in this links
https://build.openmodelica.org/omc/builds/linux/releases/1.9.3/contrib-jessie/
https://build.openmodelica.org/omc/builds/linux/releases/1.9.3/libraries/

not by command line

so I want the other steps after that please
thank you very much

**Comment by xie-dongping** [comment]
I guess you would still need admin access:
```
dpkg -i your_openmodelica_package.deb
```

And then you can skip the following steps and run the other commands in the old post:
```
for deb in deb deb-src; do echo "$deb http://build.openmodelica.org/apt `lsb_release -cs` stable"; done | sudo tee /etc/apt/sources.list.d/openmodelica.list
wget -q http://build.openmodelica.org/apt/openmodelica.asc -O- | sudo apt-key add - 
sudo apt-get update
sudo apt-get install -y openmodelica
```

However, I would simply run the command in the old post and it would be ok.

**Comment by xie-dongping** [comment]
@ahmedsami1406 
As for the right to left direction, I guess modifying the css may suffice. Like [this](http://docutils.sourceforge.net/FAQ.html#can-i-produce-documents-in-right-to-left-languages). 

You may modify the css by adding a css file called `locale/ar/ar.css` and injecting it to the standard css using the same hack I used for Chinese language `Makefile` (line 442).

**Comment by ahmedsami1406** [comment]
I did not succeed this time
I may succeed next time Insha'ALLAH
@xie-dongping

**Comment by dietmarw** [comment]
@ahmedsami1406 You can ignore the warnings about `adanced.rst` and `todo.rst`. Those are not of any importance and we all get them.

**Comment by xie-dongping** [comment]
@ahmedsami1406 
It seems the problem lies only happens by `pip install`. If this works, then it shouldn't be a problem to compile.

Are you behind a proxy? If so, you may have to add ` --proxy http://your_proxy_address:port`
```
pip install --proxy http://your_proxy_address:port --user --upgrade 'sphinx-intl==0.9.6'
```

Do the same for other pip install statements and let's see if it works.

**Comment by ahmedsami1406** [comment]
@dietmarw 
@xie-dongping 

thank you for caring> I will study your advices and try until I succeed Insha'ALLAH

**Comment by ahmedsami1406** [comment]
If right to left direction is applied then
it will be no need for \n method so I will remove all \n's
Insha'ALLAH

**Comment by xie-dongping** [comment]
Let's see if the css trick works.

**Comment by ahmedsami1406** [comment]
I didn't Understand it till Now
I will try to Understand It Insha'ALLAH
@xie-dongping

**Pull request merged**
