### PR TITLE
small part of population section

### PR DESCRIPTION
**Pull request by ahmedsami1406**

### CODE REVIEW

**Comment by ahmedsami1406** [comment]
I am sorry
I am ill now.

thank you

**Comment by xie-dongping** [comment]
Thanks!

I hope you get well soon!

**Comment by ahmedsami1406** [comment]
I am really sorry that I am very ill and I will be not able to coninue for a long period or forever
So, I want to delete my account as I am afraid that the account may be hacked

Is that have an effect on Xogeny:master and the merged translations ?

**Comment by ahmedsami1406** [comment]
this link contains the source file of arabic translation of presentation
https://www.mediafire.com/folder/a28aa3g4ofg8k/Modelica_%D9%84%D8%BA%D8%A9_%D9%85%D9%88%D8%AF%D9%84%D9%8A%D9%83%D8%A7

**Comment by ahmedsami1406** [comment]
@dietmarw 

thank you

this is the source arabic translation of martin otter's and your presentation
https://www.mediafire.com/folder/a28aa3g4ofg8k/Modelica_%D9%84%D8%BA%D8%A9_%D9%85%D9%88%D8%AF%D9%84%D9%8A%D9%83%D8%A7

**Comment by ahmedsami1406** [comment]
@xie-dongping @dietmarw @mtiller  and others

thank you all

**Comment by ahmedsami1406** [comment]
@mtiller 
my email ahmedsami1406h@gmail.com is deleted now

**Comment by xie-dongping** [comment]
@ahmedsami1406 
Sorry to hear that! I hope that you are fine.

No, if you delete your account, the master branch wouldn't be affected.

**Comment by ahmedsami1406** [comment]
@xie-dongping 
thank you for everything

Alhamdulillah I am happy but I am ill

**Comment by easyengineering** [comment]
@dietmarw 

default
I revised the presentaion translation and I found these errors> I am sorry about that

**Comment by easyengineering** [comment]
@xie-dongping @dietmarw @mtiller and others
How are you all ? I am sorry that I can not continue till now>

**Comment by xie-dongping** [comment]
@easyengineering 
PRs would certainly be welcomed.

Nice to see you! Hope you doing fine!

**Comment by easyengineering** [comment]
@xie-dongping 
I am fine and happy Alhamdulillah
I wish that Arabic translation would be finished by others> and I invited some scholars for this job>
I thank you all very much for supporting engineering to be easy.

**Comment by needrevisionorsupervision** [comment]
In The Name of ALLAH

Hi all,
@xie-dongping @dietmarw @mtiller 

I was seeking for another scholar who is more experienced than me to continue the Arabic translation of Modelica by Example. Till now I am seeking for him or seeking for revision or supervision for my translation. I was shocked because I made that fatal errors in the presentation of Martin Otter and Dietmer Winkler. I am sorry for them and for you all. Till now I could not edit the presentation to fix my fatal errors as the site is under development.
http://kutub.info/library/book/19510
I tried to make a note about that on facebook engineering Arabic groups but a got a little interaction.

Now, I want to continue my translation with this account named "Need Revision or Supervision".  Is that
a) good because doing anything is better than doing nothing ?
b) bad because reparation is harder than establishment ?
I want a feedback from you as an author or an English language supervisor.
--------------------------------------------------------------------------------------
note: I translated Alhamdulillah part of the wikipedia article about Modelica into Arabic with others:

http://www.marefa.org/index.php/%D9%85%D9%88%D8%AF%D9%84%D9%8A%D9%83%D8%A7

https://ar.wikipedia.org/wiki/%D9%85%D9%88%D8%AF%D9%8A%D9%84%D9%8A%D9%83%D8%A7

**Comment by needrevisionorsupervision** [comment]
In The Name of ALLAH

this is a clarification for the errors:

"Potential": I translated it into "الجهد الكهربي" Which means Voltage
"Flow": I translated it into "سريان المائع" Which means fluid flow
"Stream": I translated it into "تدفق المائع" Which means Fluid stream

I am sorry. (specially for Martin Otter and Dietmer Winkler)

@xie-dongping @mtiller @dietmarw

**Comment by dietmarw** [comment]
@needrevisionorsupervision No problem with the errors you found. That document is just meant to be a basis and you should perhaps also keep it up to date. Since the version you translated is from 2013 it will have outdated information regarding the available Modelica, Modelica Standard Library versions and available tools. The Licence it is under (CC-SA) allows you also to update the content also for the translated version without having to ask the original authors (Martin Otter, me) for permission.

Which you all the best with your translation efforts as they are very much appreciated.

**Comment by needrevisionorsupervision** [comment]
@dietmarw 
Thank you very much

**Comment by needrevisionorsupervision** [comment]
@dietmarw @xie-dongping @mtiller 
your efforts are also appreciated for me.

**Pull request merged**
