### PR TITLE
Update Rod_ArrayComprehensionsOneEquation.mo

### PR DESCRIPTION
**Pull request by mromanoni**
According to previous and following physical model added if statement to consider convective term only on the first and last element of the discretization

### CODE REVIEW

**Comment by xogeny** [comment]
This is definitely an error in that chapter.  But this isn't the correct solution.  The intention was that there is heat transfer from each section to the ambient (not just the first and the last).  You can see this not just in the text (e.g., "convection from each section to some ambient temperature") but also in the equation right before the "Implementation" section (note the last term):

```
\rho A L_i C \frac{\mathrm{d} T_i}{\mathrm{d}t} &= -k
A\frac{T_i-T_{i-1}}{L_i} -k A\frac{T_i-T_{i+1}}{L_i} -h A (T_i-T_{amb})
```

So the equation you are changing is actually correct.  The correction should be to add the convection term for **all** nodes (all values of *i*).

Thanks for catching this.  Feel free to adjust your pull request.

**Comment by dietmarw** [comment]
@mtiller I thought to fix this but looking at the code again, the convection term is actually present in all nodes. The only thing I found is that it is missing the Area. So my suggestion would be to fix it like this

```diff
-  rho*V*C*der(T) = {-h*(T[i]-Tamb)
￼+  rho*V*C*der(T) = {-h*A*(T[i]-Tamb)
￼                    -(if i==1 then 0 else k*A/(L/n)*(T[i]-T[i-1]))
                    -(if i==n then 0 else k*A/(L/n)*(T[i]-T[i+1])) for i in 1:n};
```

**Comment by xogeny** [comment]
I think there is another issue in this model.  We do not distinguish between cross-sectional area and surface area (even in the text).  So this is also a mistake.  Plus, the mistake originally pointed out still looks like it is there in the for loop part.  So I'll need to review all the models and the text to patch this up.  Unless somebody seems something I'm missing here?

**Comment by dietmarw** [comment]
Yes I actually was wondering which area A should be representing. So the model seems to be flawed and I agree the whole sections needs to be revisited.

**Comment by xogeny** [comment]
This has been addressed by other changes.

**Pull request closed without merging**
