### PR TITLE
First group of translated files (some of then reviewed)

### PR DESCRIPTION
**Pull request by sulopezperez**

### CODE REVIEW

**Comment by xie-dongping** [comment]
@xogeny 
Mike, do we want to merge this version?

**Comment by dietmarw** [comment]
I was wondering the same. Problem is that it now has some merge conflicts. So someone has to go through it.

**Comment by xie-dongping** [comment]
Yeah, then let me do it. Easter might be great.

**Comment by dietmarw** [comment]
Excellent. :+1:

**Comment by xie-dongping** [comment]
@sulopezperez  @dietmarw 
Everything merged except for dedication.po, since it is apparently already translated. 

So I just left it as it is. For the Spanish language translation, I think a coordinator would be necessary for this situation.

**Pull request merged**
