### PR TITLE
Update the Dockerfile to enable streamlined building process

### PR DESCRIPTION
**Pull request by xie-dongping**
Add build scripts for Dockerbuild to address wishes in #250 

One can use the docker build with: (remember to clear cache before running)
```
cd docker
make S3FLAGS="--secret_key=longkey --access_key=shortkey" build_master
```

Since it only works with the newset version of s3cmd, the book-PY Dockerfile is also changed.

The build process itself is controlled by text/build_all.sh to resolve the dependencies problems for plots in different langauges.

### CODE REVIEW

**Comment by xogeny** [comment]
First, if I understand your build process you are not putting the access or secret keys anywhere in the image.  If so, **good**.  This is a principle I always try to follow.  If I further understand this approach, you bundle these up as a command line argument in the `run` command in an environment variable you pass to s3cmd.

But here is my question.  I thought `s3cmd` could pick up `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` through on the command line.  In other words, instead of pulling these together as a special environment variable `S3FLAGS` that can only be used by a specific version of `s3cmd`, wouldn't it be possible to set this up using `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` and have it work with any version of `s3cmd`?  Or am I missing something?

Thanks.

**Comment by xie-dongping** [comment]
Both of the command line options of `s3cmd` are only available at v1.6
```
--access_key=ACCESS_KEY
--secret_key=SECRET_KEY
```

`S3FLAGS` is not a special environmental variable, it is just a way for you to change `s3cmd` command line options in the `Makefile`. The environmental variable itself work for all `s3cmd` version. It is just that not command line options are supported by `s3cmd`.

**Comment by xogeny** [comment]
@xie-dongping I don't think I explained the issue that well.  My point was, instead of putting a `-e S3FLAGS=...`, why not simply have `-e AWS_ACCESS_KEY_ID=...` and `-e AWS_SECRET_ACCESS_KEY=...` in the command line.  My recollection was that if these variables are set, s3cmd will use them.  That way, you could use any version of `s3cmd` and you wouldn't have to know the exact syntax of the command line arguments to `s3cmd`.  Also, any other commands that might want to interact with S3 should also use these environment variables (since these are, as far as I know, the standard environment variable names across S3 clients).  Or, does that not work?

**Comment by xie-dongping** [comment]
That will be really nice if it works that way.  I can have a look tomorrow, and see if it works for the `s3cmd` version in ubuntu 14.04 LTS. 

If it works, then we should use this variant. Since it is the variant that the standard `aws` program uses.

**Comment by xie-dongping** [comment]
Now it works by using the environmental variable in the configuration file. This is a feature of version 1.5 (the version supported by 14.04 LTS). 

I have tested it with my own s3 bucket. 

However, the deployment of the printed document is not tested since it is on files.xogeny.com.

I still want to put the BUCKET name into a environmental variable, so you can change the deployment address easily. Some time in the week.

**Pull request merged**
